---
-       hosts: all
        become: true
        tasks: 
          -     name: copy war onto tomcat server
                copy:
                  src: /var/lib/jenkins/workspace/credit/target/
                  dest: /opt/apache-tomcat-8.5.78/webapps/webapp/
        
                
                
